package config

var SIMULATION_DURATION_HOUR = 3 * 30 * 24

var SHOWER_TIME = []int{6, 17}

const MEAN_LAUNDRY_DURATION_HOUR = 24
const MIN_LAUNDRY_DURATION_HOUR = 24

const MEAN_HOUR_UNTIL_NEXT_LAUNDRY = 1
const MIN_HOUR_UNTIL_NEXT_LAUNDRY = 0
