package config

var SIMULATION_DURATION_HOUR = 10 * 365 * 24

var SHOWER_TIME = []int{6, 17}

const MEAN_LAUNDRY_DURATION_HOUR = 24
const STD_LAUNDRY_DURATION_HOUR = 3

const MEAN_HOUR_UNTIL_NEXT_LAUNDRY = 24
const STD_HOUR_UNTIL_NEXT_LAUNDRY = 24
